### PR TITLE
feat: add support for auto-unpin on merged/closed, closes #5

### LINKED ISSUE #5: Auto unpin on merged/closed

### PR DESCRIPTION
**Pull request by exbotanical**
Alright, here we go!

A couple of thoughts:

During local dev, I encountered GitHub's API rate limiting and had to temporarily modify the `fetch` utility to use a PAT. This is definitely an edge-case, as I had adjusted the TTL to a very small interval for testing purposes, but I imagine other devs _may_ run into this. In any case, have you considered adding an option to make authenticated requests? 

Second, do you plan on adding testing to this project? I'd be happy to write a few unit tests so we have coverage of this feature. 

Anyway, give me a shout if I can correct anything on this PR.  Thanks for letting me join in :)

### CODE REVIEW

**Comment by antfu** [comment]
We'd better to add an option to the popup.

> PAT

Created #12 

> Testing

That would be great, thanks!

**Comment by exbotanical** [comment]
@antfu What framework / tooling do you prefer for testing? I can set it up in this PR or I can hold off and add my tests later if you would prefer to do it. I'm happy with any approach!

**Comment by antfu** [comment]
I have no idea how to test a web extension, maybe Cypress could do.

**Comment by exbotanical** [comment]
> I have no idea how to test a web extension, maybe Cypress could do.

Same. I'm hoping worst case scenario we will at least be able to stub some of the functionality. I'll do a bit of research and give it a shot!

**Comment by exbotanical** [comment]
Well dang, integration testing web extensions is trickier than I thought. I don't think I'm going to figure this one out in a reasonable amount of time. Sorry :/

It looks like there's a few discussions on Cypress' GH about mocking some of the Chrome integrations. Maybe someone that is familiar with testing extensions can chime in.

**Comment by antfu** [comment]
No problem at all. Since currently, we don't have much complex logic to handle, let's hold the testing for later. Thanks.

**Comment by antfu** [comment]
Note: I have merged it for now. However, we will need to add a UI entry in the popup to make it visible for users to configure. Again, PR is welcome.

Thanks

**Pull request merged**
